imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php:
            version: 7.1       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm

    dependencies:
        before:
            -
                command: "mkdir build"
        after:
            - "composer require --dev phpunit/phpunit"

    tests:
        override:
            -
                command: "vendor/bin/phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/logs/clover.xml"
                    format: "php-clover"
